version: 3
files:
  - pattern: .github/workflows/*.yml
  - pattern: .github/workflows/*.yaml
  - pattern: .github/actions/*/action.yml
  - pattern: .github/actions/*/action.yaml

ignore_actions:
  - name: Homebrew/actions/.*
    ref: .*
  - name: yamadashy/repomix/.github/actions/repomix
    ref: .*
