name: 🚀 Feature Request
description: Suggest an idea or improvement for Repomix
labels:
  - enhancement
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve Repomix!

        We appreciate your feedback and will review your request as soon as possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "A clear and concise description of the feature you’d like to see."
      placeholder: |
        e.g. Add support for a `.repomixignore` file to exclude certain paths when packing.
    validations:
      required: true
