name: 🐛 Bug Report
description: Report an unexpected behavior or error in Repomix
labels:
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue! We appreciate your help in making Repomix better.

        If you need real-time support, feel free to join our [Discord server](https://discord.gg/wNYzTwZFku).

        Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Please provide a concise description of what happened."
      placeholder: |
        e.g. Running `repomix --version` prints an error instead of the version.
    validations:
      required: true

  - type: dropdown
    id: usage_context
    attributes:
      label: Usage Context
      description: "Where did you encounter this issue?"
      options:
        - Repomix CLI
        - repomix.com

  - type: input
    id: repomix_version
    attributes:
      label: Repomix Version
      description: "Output of `repomix --version`"
      placeholder: "e.g. v0.3.5"

  - type: input
    id: node_version
    attributes:
      label: Node.js Version
      description: "Output of `node --version`"
      placeholder: "e.g. v18.16.0"
