name: Homebrew

on:
  release:
    types:
      - created

jobs:
  homebrew:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          test-bot: false

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@main

      - name: Bump packages
        uses: Homebrew/actions/bump-packages@main
        with:
          token: ${{ secrets.COMMITTER_TOKEN }}
          formulae: repomix
